# Generated by Django 5.2.4 on 2025-07-22 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_tarefa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='fim',
            new_name='data_fim',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='inicio',
            new_name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='concluida',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GoogleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.TextField()),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('scopes', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
