# Generated by Django 5.2.4 on 2025-07-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_fim_tarefa_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='color_id',
            field=models.CharField(default='8', max_length=2),
        ),
        migrations.DeleteModel(
            name='GoogleCredentials',
        ),
    ]
