# Generated by Django 5.2.4 on 2025-07-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_tarefa_color_id_delete_googlecredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
